🚧 Update to SDK 26.7.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🦊👨🏻‍🦽🖐🏻👹

Full error log:
Error:  asset 2022-7-26--16-6-1--b3cf3043-9d68-4b73-91b5-a349f5b0ff1d/main.min.js 192 KiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 165 KiB
modules by path ./node_modules/destroyable/dist/ 38 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.4 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB 2 modules
modules by path ./node_modules/waitasecond/dist/ 16.9 KiB 11 modules
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 83.6 KiB [built] [code generated]
./node_modules/xyzt/dist/main.js 26.4 KiB [built] [code generated]
modules by path ./src/ 9.99 KiB
modules by path ./src/randomness-distribution/generators/*.tsx 1.79 KiB 5 modules
modules by path ./src/randomness-distribution/*.tsx 4.55 KiB 2 modules
./src/index.ts 146 bytes [built] [code generated]
./src/randomness-distribution/utils/randomInteger.tsx 231 bytes [built] [code generated]
./src/randomness-distribution/components/RandomnessChartComponent.tsx 3.28 KiB [built] [code generated]
./package.json 811 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\playground\src\randomness-distribution\randomness-chart-art.tsx
./src/randomness-distribution/randomness-chart-art.tsx 1:42-58
[tsl] ERROR in C:\Users\me\work\collboard\playground\src\randomness-distribution\randomness-chart-art.tsx(1,43)
TS2305: Module '"@collboard/modules-sdk"' has no exported member 'ISystemsExtended'.
@ ./src/randomness-distribution/randomness-distribution.tsx 20:31-64
@ ./src/index.ts 3:0-64

webpack 5.35.1 compiled with 1 error in 6521 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\playground\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\playground\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\playground\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\playground\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\playground\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\playground\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\playground\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\playground\node_modules\webpack\lib\Watching.js:201:28)